---
title: "Conclusion"
format: html
editor: visual
---

As seen in the results above, there are several features of a flight that can predict whether or not a passenger will report satisfaction after their flight experience. Enhancing customer satisfaction should be a priority for airlines so that they can have customer retention as well as gain new customers. Looking at what determines the satisfaction levels of customers can be critical information for airlines as they look to improve their businesses. As reported above, the most important factors for customer satisfaction are type of travel, online boarding satisfaction, and customer type. There seems to be a bit of a trend in the type of factors that are important to passengers and their satisfaction. A lot of the lower ranked factors have to do with the luxuriousness of the experience. This category includes things like food and drink service, in-flight entertainment, and comfortability of the seat. On the other hand, factors having to do with convenience and efficiency rank higher in the importance for customer satisfaction. These include factors such as check-in service, boarding service, inflight internet, and convenience of the departure and arrival time. This pattern indicates that there has been a possible shift from the majority of passengers looking for a luxury flight experience to the majority of passengers looking for ease and convenience in their travels.

Type of travel is a factor that refers to whether the passenger is traveling for business or for leisure. It is interesting to note that the most important factor for predicting satisfaction is one that is not in the airline’s control– people traveling for business will travel for business and people traveling for leisure will travel for leisure. While this alone does not give an airline a lot to go off of for improving their customer satisfaction, it may be interesting to use this information to segment the customer base into different groups. Repeating this analysis with the data separated into people traveling for business and people traveling for leisure may show which segment of the consumer base is generally more satisfied. This breakdown can also show how the importance of factors varies amongst these two different groups. Some factors may be much more important for satisfaction for those traveling for leisure than they are for those traveling for business. If this is the case, then it would be the most impactful for the airlines to target the factors that are most important to the segment of the consumer base that tends to be less satisfied with their flight experiences.

Another important factor of note is the type of customer that is traveling. The two types of customer that this analysis examines are loyal customers and non-loyal customers. Looking at which of the two groups of customers is generally more satisfied with their experience could provide valuable insight to airlines. If loyal customers are the less satisfied group, then the airline should look into improving their frequent flier loyalty programs. If non loyal customers are the less satisfied group, then the airline could look into expanding their frequent flier loyalty programs to include a larger base that will be more likely to be satisfied with their experience.

Delays (both in arrival time and departure time) also have a pretty great impact on a passenger’s satisfaction as we can see from the Generalized Additive Models. This is a factor that could be in an airline’s control depending on the context but oftentimes is also due to external factors such as weather and air traffic. Despite not necessarily being in the control of the airline, the probability of dissatisfaction among passengers who experienced delays means that airlines should probably look further into what possible options there are for improving the experience of customers during some of the inevitable delays.
