---
title: "Introduction"
---

US airlines transported 751.4 million passengers in 2023 both domestically and internationally. With such a high number of people taking flights every year, airlines have a vested interest in maintaining the satisfaction of their customers in order to ensure their profits in a competitive market. This is especially true due to the highly competitive nature of the airline industry. With numerous airlines vying for passengers' business, customer satisfaction is a key differentiator, with satisfied customers more likely to choose airline services again in the future, contributing to loyalty and repeat business.
We intend to analyze a dataset which surveys airline passengers on various different aspects of their experience flying with the given airline and then asks whether they were satisfied with the experience as a whole. Our analysis will attempt to determine whether the satisfaction of a passenger can be predicted based on the surveyed features, and if so, which aspects of a flight have the greatest level of impact on a passenger’s overall satisfaction. 
Our goal in this analysis would be to provide airlines with a guide on which areas would be most efficient to improve for customer retainment.  This strategic approach ensures that airlines can allocate resources efficiently, focusing on areas that yield the highest returns in terms of customer satisfaction and, ultimately, loyalty. By addressing the key pain points identified through our analysis, airlines can cultivate a more positive and fulfilling travel experience for passengers, thereby bolstering their chances of retaining customers in an increasingly competitive market. The three models we intend to utilize to analyze this data are a Support Vector Machine Model, a Logistic regression model, and a Generalized Additive Model. 

In conducting this analysis, we have also looked into multiple studies regarding predicting the satisfaction of airline passengers. The J.D. Power 2023 North America Airline Satisfaction Study discusses a paradox in the aviation industry, where, despite record revenues driven by high demand and limited supply, customer satisfaction with major airlines is declining due to soaring airfares, staffing shortages, and reduced routes. Low-cost carriers face particular challenges, where passengers seek airfare bargains. In contrast, first-class passengers’ experience improved satisfaction, attributed to enhanced food and beverage services. (2023 North America Airline Satisfaction Study, 2023)
The study Forecast and analysis of aircraft passenger satisfaction based on RF-RFE-LR model, discusses how the civil aviation industry faced profound challenges, and how addressing passenger satisfaction became crucial for airlines in lieu of a decrease in travel demand. This study explored predictive models and factors influencing passenger satisfaction, emphasizing the importance of service quality in retaining customers. Various methodologies, including machine learning algorithms and feature selection techniques, were employed in this study to extract key factors affecting passenger satisfaction. (Jiang et al., 2024)

The study the impact of the COVID-19 pandemic on airlines’ passenger satisfaction investigates airline passenger satisfaction trends before and during the COVID-19 pandemic by analyzing influential factors using a dataset of 9745 passenger reviews from airlinequality.com. Sentiment analysis and machine learning algorithms conducted in this study show a decline in satisfaction post-pandemic, with staff behavior emerging as a crucial factor. Addressing negative sentiments emerged, through predictive modeling, as one of the most important factors in customer satisfaction. (The Impact of the COVID-19 Pandemic on Airlines' Passenger Satisfaction, 2023)